import { Employee } from "./employees.js";
import { Animal } from "./animals.js";

export const runSeed = async () => {
    try {
        const employeesCount = await Employee.count();
        if (employeesCount === 0) {
            await Employee.bulkCreate([
            {
                first_name: "Andrei",
                last_name: "Buzagiu",
                email: "andrei.buzagiu@gmail.com",
                password: "admin123",
                phone_number: "0756056577",
                role: "admin"
            },
            {
                first_name: "Vlăduț",
                last_name: "Alexa",
                email: "vladut.alexa@gmail.com",
                password: "staff123",
                phone_number: "0756056567",
                role: "staff"
            },
            {
                first_name: "Alina",
                last_name: "Constantin",
                email: "alina.constantin@gmail.com",
                password: "staff123",
                phone_number: "0742157866",
                role: "staff"
            },
            {
                first_name: "Gabriel",
                last_name: "Truică",
                email: "gabriel.truica@gmail.com",
                password: "staff123",
                phone_number: "0742689511",
                role: "staff"
            }
        ], { individualHooks: true });
            console.log("Admin user created successfully.");
        }

        const animalsCount = await Animal.count();
        if (animalsCount === 0) {
            await Animal.bulkCreate([
                {
                    name: "Buddy",
                    species: "Dog",
                    breed: "Golden Retriever",
                    age: 3,
                    gender: "Male",
                    size: "Large",
                    color: "Golden",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2024-12-20",
                    notes: "Very friendly and great with kids.",
                    image: "https://bucuriacasei.ro/wp-content/uploads/2024/02/rasa-golden-retriever-scaled.webp",
                    microchip_number: "123456789012356"
                },
                {
                    name: "Whiskers",
                    species: "Cat",
                    breed: "Siamese",
                    age: 2,
                    gender: "Female",
                    size: "Medium",
                    color: "Cream with dark brown points",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2024-11-15",
                    notes: "Loves to cuddle and has a playful personality.",
                    image: "https://cdn-aahmh.nitrocdn.com/mwIJloVUffDtKiCgRcivopdgojcJrVwT/assets/images/optimized/rev-31cad3f/www.cozycatfurniture.com/image/siamese-cat-cover.jpg",
                    microchip_number: "123456789012357"
                },
                {
                    name: "Thumper",
                    species: "Rabbit",
                    breed: "Holland Lop",
                    age: 1,
                    gender: "Male",
                    size: "Small",
                    color: "white with brown spots",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "reserved",
                    arrival_date: "2025-02-15",
                    notes: "Energetic and loves to hop around. Very friendly with children.",
                    image: "https://everbreed.com/wp-content/uploads/2024/02/Holland_lop_rabbit-scaled.jpg",
                    microchip_number: "123456789012358"
                },
                {
                    name: "Rio",
                    species: "Parrot",
                    breed: "Macaw",
                    age: 4,
                    gender: "Female",
                    size: "Medium",
                    color: "Blue and yellow",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "adopted",
                    arrival_date: "2025-02-10",
                    notes: "Loves to talk and mimic sounds. Very social and intelligent.",
                    image: "https://images.takeshape.io/86ce9525-f5f2-4e97-81ba-54e8ce933da7/dev/bebc6dc3-7ca9-4157-a176-a7d244018f0f/Blue%20Hyacinth%20macaw%20parrot%20in%20its%20natural%20environment%20dreamstime_xxl_5040987.jpeg?auto=compress%2Cformat&w=1440",
                    microchip_number: "123456789012359"
                },
                {
                    name: "Tigrese",
                    species: "Cat",
                    breed: "Bengal",
                    age: 2,
                    gender: "Female",
                    size: "Small",
                    color: "Brown spotted",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2023-10-01",
                    notes: "Very playful and affectionate.",
                    image: "https://www.dailypaws.com/thmb/SgHjwVWrjBliHcmCmnfyNP2T6t8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/bengal-wood-walking-867775498-2000-f79225d86f32493998e5cdd98451da82.jpg",
                    microchip_number: "123456789012345",
                  },
                  {
                    name: "Max",
                    species: "Dog",
                    breed: "Siberian Husky",
                    age: 4,
                    gender: "Male",
                    size: "Large",
                    color: "Black",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "reserved",
                    arrival_date: "2023-09-15",
                    notes: "Friendly and loves to swim.",
                    image: "https://a-us.storyblok.com/f/1016262/4256x2832/9dcacc41fe/siberian-husky.jpeg",
                    microchip_number: "123456789012346",
                  },
                  {
                    name: "Milo",
                    species: "Dog",
                    breed: "Beagle",
                    age: 3,
                    gender: "Male",
                    size: "Medium",
                    color: "Brown",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2024-01-10",
                    notes: "Energetic and curious.",
                    image: "https://www.cacciapassione.com/wp-content/uploads/2019/03/beagle.jpg",
                    microchip_number: "123456789012347",
                  },
                  {
                    name: "Cleo",
                    species: "Cat",
                    breed: "British Shorthair",
                    age: 5,
                    gender: "Female",
                    size: "Small",
                    color: "Gray",
                    health_status: "Sick",
                    vaccinated: false,
                    sterilized: true,
                    adoption_status: "adopted",
                    arrival_date: "2023-11-20",
                    notes: "Recovering from illness.",
                    image: "https://cdn.royalcanin-weshare-online.io/mVbc9noBBKJuub5qA7pQ/v3/bp-lot-2-british-shorthair-color-outdoor",
                    microchip_number: "123456789012348",
                  },
                  {
                    name: "Toby",
                    species: "Dog",
                    breed: "Golden Retriever",
                    age: 6,
                    gender: "Male",
                    size: "Large",
                    color: "Golden",
                    health_status: "Under treatment",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "available",
                    arrival_date: "2024-02-05",
                    notes: "Undergoing physiotherapy.",
                    image: "https://mediacdn.libertatea.ro/unsafe/1200x0/smart/filters:format(webp):contrast(8):quality(75)/https://static4.libertatea.ro/wp-content/uploads/2020/09/golden-retriever-cat-de-usor-se-dreseaza-si-ce-personalitate-are-cel-mai-indragit-caine.jpg",
                    microchip_number: "123456789012349",
                  },
                  {
                    name: "Hazel",
                    species: "Rabbit",
                    breed: "Rex",
                    age: 4,
                    gender: "Male",
                    size: "Medium",
                    color: "Beige",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2023-12-10",
                    notes: "Friendly with kids.",
                    image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Fast_Track%2C_Lilac_Mini_Rex.jpg",
                    microchip_number: "123456789012363",
                  },
                  {
                    name: "Coco",
                    species: "Rabbit",
                    breed: "Mini Rex",
                    age: 2,
                    gender: "Female",
                    size: "Small",
                    color: "White",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "adopted",
                    arrival_date: "2024-01-05",
                    notes: "Quiet and gentle.",
                    image: "https://www.thesprucepets.com/thmb/VYDopMBfK6m_aCTAgiShehlZChE=/2048x0/filters:no_upscale():strip_icc()/Mini_rex_bunny-0bc79db3d2d54b53a9fc18e54e479883.jpeg",
                    microchip_number: "123456789012364",
                  },
                  {
                    name: "Kiwi",
                    species: "Parrot",
                    breed: "Budgerigar",
                    age: 1,
                    gender: "Male",
                    size: "Small",
                    color: "Green",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "available",
                    arrival_date: "2024-02-01",
                    notes: "Chirpy and talkative.",
                    image: "https://i0.wp.com/www.australiangeographic.com.au/wp-content/uploads/2021/10/Budgerigar-fact-file.jpg?fit=1800%2C946&ssl=1",
                    microchip_number: "123456789012365",
                  },
                  {
                    name: "Luna",
                    species: "Parrot",
                    breed: "Cockatiel",
                    age: 2,
                    gender: "Female",
                    size: "Small",
                    color: "Yellow",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "reserved",
                    arrival_date: "2024-02-10",
                    notes: "Loves music.",
                    image: "https://media.zenfs.com/en/parade_pets_articles_328/06fb5fa596e6a9c7405d06d921e6a141",
                    microchip_number: "123456789012366",
                  },
                  {
                    name: "Bella",
                    species: "Dog",
                    breed: "Poodle",
                    age: 2,
                    gender: "Female",
                    size: "Small",
                    color: "White",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2024-01-20",
                    notes: "Loves to be groomed.",
                    image: "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2023/09/06151834/Poodle-standing-in-the-garden.jpg",
                    microchip_number: "123456789012350",
                  },
                  {
                    name: "Rocky",
                    species: "Dog",
                    breed: "Boxer",
                    age: 5,
                    gender: "Male",
                    size: "Large",
                    color: "Brown",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "reserved",
                    arrival_date: "2023-08-30",
                    notes: "Protective and loyal.",
                    image: "https://cdn.britannica.com/46/233846-050-8D30A43B/Boxer-dog.jpg",
                    microchip_number: "123456789012351",
                  },
                  {
                    name: "Snowball",
                    species: "Rabbit",
                    breed: "Dutch",
                    age: 1,
                    gender: "Female",
                    size: "Small",
                    color: "White",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2024-03-01",
                    notes: "Very soft and calm.",
                    image: "https://www.thesprucepets.com/thmb/qs-qLxHPeQRsj9QSHItpaFTwjOc=/2020x0/filters:no_upscale():strip_icc()/GettyImages-153016104-2e02cc46fd854d30a0e1eaabab6ea82e.jpg",
                    microchip_number: "123456789012360",
                  },
                  {
                    name: "Fluffy",
                    species: "Rabbit",
                    breed: "Angora",
                    age: 3,
                    gender: "Female",
                    size: "Small",
                    color: "Brown",
                    health_status: "Under treatment",
                    vaccinated: false,
                    sterilized: false,
                    adoption_status: "reserved",
                    arrival_date: "2024-01-20",
                    notes: "Requires daily brushing.",
                    image: "https://www.zooplus.co.uk/magazine/wp-content/uploads/2022/03/white-angora-rabbit-on-grass.jpeg",
                    microchip_number: "123456789012362",
                  },
                  {
                    name: "Zara",
                    species: "Cat",
                    breed: "Persian",
                    age: 3,
                    gender: "Female",
                    size: "Small",
                    color: "Cream",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2023-12-01",
                    notes: "Calm and elegant.",
                    image: "https://cdn.prod.website-files.com/659c0b0024c127bdbe890959/673a2eb3c1d361675009f9b7_31.jpg",
                    microchip_number: "123456789012352",
                  },
                  {
                    name: "Simba",
                    species: "Cat",
                    breed: "Maine Coon",
                    age: 4,
                    gender: "Male",
                    size: "Large",
                    color: "Orange",
                    health_status: "Sick",
                    vaccinated: false,
                    sterilized: false,
                    adoption_status: "available",
                    arrival_date: "2024-03-10",
                    notes: "Needs a special diet.",
                    image: "https://catastic.pet/wp-content/uploads/2023/03/maine-coon-origin.jpg",
                    microchip_number: "123456789012353",
                  },
                  {
                    name: "Daisy",
                    species: "Dog",
                    breed: "Shih Tzu",
                    age: 1,
                    gender: "Female",
                    size: "Small",
                    color: "Black and white",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: true,
                    adoption_status: "reserved",
                    arrival_date: "2024-02-28",
                    notes: "Tiny and cheerful.",
                    image: "https://mediacdn.libertatea.ro/unsafe/1260x708/smart/filters:format(webp):contrast(8):quality(75)/https://static4.libertatea.ro/wp-content/uploads/2020/09/shih-tzu-cum-se-ingrijeste-un-caine-de-rasa--ce-personalitate-are-shih-tzu.jpg",
                    microchip_number: "123456789012354",
                  },
                  {
                    name: "Mango",
                    species: "Parrot",
                    breed: "Lovebird",
                    age: 3,
                    gender: "Male",
                    size: "Small",
                    color: "Orange",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "available",
                    arrival_date: "2024-03-05",
                    notes: "Very curious and playful.",
                    image: "https://cdn.download.ams.birds.cornell.edu/api/v2/asset/623495051/1200",
                    microchip_number: "123456789012367",
                  },
                  {
                    name: "Skye",
                    species: "Parrot",
                    breed: "Macaw",
                    age: 5,
                    gender: "Female",
                    size: "Large",
                    color: "Blue",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "available",
                    arrival_date: "2023-11-01",
                    notes: "Needs space to fly.",
                    image: "https://lafeber.com/pet-birds/wp-content/uploads/2024/11/shutterstock_2052377168.jpg",
                    microchip_number: "123456789012368",
                  },
                  {
                    name: "Oscar",
                    species: "Dog",
                    breed: "Dachshund",
                    age: 4,
                    gender: "Male",
                    size: "Small",
                    color: "Brown",
                    health_status: "Under treatment",
                    vaccinated: false,
                    sterilized: true,
                    adoption_status: "available",
                    arrival_date: "2024-03-15",
                    notes: "Has a leg injury.",
                    image: "https://images.ctfassets.net/550nf1gumh01/yh0l63Foctzv7067YDNhO/e391cd9ef39818a77484e5b1fd29f5bc/iStock-145053225.jpg?q=90&w=1240",
                    microchip_number: "123456789012355",
                  },
                  {
                    name: "Coco",
                    species: "Parrot",
                    breed: "African Grey",
                    age: 6,
                    gender: "Male",
                    size: "Medium",
                    color: "Grey",
                    health_status: "Healthy",
                    vaccinated: true,
                    sterilized: false,
                    adoption_status: "adopted",
                    arrival_date: "2023-10-20",
                    notes: "Extremely intelligent.",
                    image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Psittacus_erithacus_-perching_on_tray-8d.jpg",
                    microchip_number: "123456789012369",
                  }
            ]);
            console.log("Animals added successfully.");
        }

    } catch (err) {
        console.error("Error in seeding data:", err);
    }
};
