import { Animal } from "../models/animal.js";
import {
    SPECIES,
    GENDERS,
    SIZES,
    HEALTH_STATUSES,
    ADOPTION_STATUSES,
} from "../constants/enums.js";

export const seedAnimals = async () => {
    const existing = await Animal.count();

    if (existing === 0) {
        await Animal.bulkCreate([
            {
                name: "Buddy",
                species: SPECIES.CÂINE,
                breed: "Golden Retriever",
                age: 3,
                gender: GENDERS.MASCUL,
                size: SIZES.MARE,
                color: "Auriu",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-12-20",
                notes: "Foarte prietenos și grozav cu copiii.",
                image: "https://bucuriacasei.ro/wp-content/uploads/2024/02/rasa-golden-retriever-scaled.webp",
                microchip_number: "123456789012345"
            },
            {
                name: "Whiskers",
                species: SPECIES.PISICĂ,
                breed: "Siameză",
                age: 2,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MEDIU,
                color: "Crem cu extremități maro închis",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-11-15",
                notes: "Adoră să fie alintată și are o personalitate jucăușă.",
                image: "https://www.cozycatfurniture.com/image/cache/siamese-cat-cover-1054x791.jpg",
                microchip_number: "123456789012346"
            },
            {
                name: "Thumper",
                species: SPECIES.IEPURE,
                breed: "Holland Lop",
                age: 1,
                gender: GENDERS.MASCUL,
                size: SIZES.MIC,
                color: "Maro deschis",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2025-02-15",
                notes: "Energic și adoră să sară prin jur. Foarte prietenos cu copiii.",
                image: "https://everbreed.com/wp-content/uploads/2024/02/Holland_lop_rabbit-scaled.jpg",
                microchip_number: "123456789012347"
            },
            {
                name: "Rio",
                species: SPECIES.PAPAGAL,
                breed: "Macaw",
                age: 4,
                gender: GENDERS.MASCUL,
                size: SIZES.MIC,
                color: "Albastru regal",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2025-02-10",
                notes: "Adoră să vorbească și să imite sunete. Foarte sociabilă și inteligentă.",
                image: "https://images.takeshape.io/86ce9525-f5f2-4e97-81ba-54e8ce933da7/dev/bebc6dc3-7ca9-4157-a176-a7d244018f0f/Blue%20Hyacinth%20macaw%20parrot%20in%20its%20natural%20environment%20dreamstime_xxl_5040987.jpeg?auto=compress%2Cformat&w=1440",
                microchip_number: "123456789012348"
            },
            {
                name: "Tigress",
                species: SPECIES.PISICĂ,
                breed: "Bengaleză",
                age: 2,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MEDIU,
                color: "Maro cu pete maro închis",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-10-01",
                notes: "Foarte jucăușă și afectuoasă.",
                image: "https://www.dailypaws.com/thmb/SgHjwVWrjBliHcmCmnfyNP2T6t8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/bengal-wood-walking-867775498-2000-f79225d86f32493998e5cdd98451da82.jpg",
                microchip_number: "123456789012349",
            },
            {
                name: "Max",
                species: SPECIES.CÂINE,
                breed: "Husky Siberian",
                age: 2,
                gender: GENDERS.MASCUL,
                size: SIZES.MARE,
                color: "Negru și alb",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-09-15",
                notes: "Prietenos și adoră să înoate.",
                image: "https://a-us.storyblok.com/f/1016262/4256x2832/9dcacc41fe/siberian-husky.jpeg",
                microchip_number: "123456789012350",
            },
            {
                name: "Milo",
                species: SPECIES.CÂINE,
                breed: "Beagle",
                age: 3,
                gender: GENDERS.MASCUL,
                size: SIZES.MEDIU,
                color: "Negru și maro-ruginiu",
                health_status: HEALTH_STATUSES.BOLNAV,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-01-10",
                notes: "Energic și curios.",
                image: "https://www.cacciapassione.com/wp-content/uploads/2019/03/beagle.jpg",
                microchip_number: "123456789012351",
            },
            {
                name: "Cleo",
                species: SPECIES.PISICĂ,
                breed: "British Shorthair",
                age: 4,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MEDIU,
                color: "Gri",
                health_status: HEALTH_STATUSES.SUB_TRATAMENT,
                vaccinated: false,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-11-20",
                notes: "Se recuperează după o boală.",
                image: "https://cdn.royalcanin-weshare-online.io/mVbc9noBBKJuub5qA7pQ/v3/bp-lot-2-british-shorthair-color-outdoor",
                microchip_number: "123456789012352",
            },
            {
                name: "Toby",
                species: SPECIES.CÂINE,
                breed: "Golden Retriever",
                age: 2,
                gender: GENDERS.MASCUL,
                size: SIZES.MEDIU,
                color: "Auriu",
                health_status: HEALTH_STATUSES.SUB_TRATAMENT,
                vaccinated: true,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-02-05",
                notes: "Urmează ședințe de fizioterapie.",
                image: "https://mediacdn.libertatea.ro/unsafe/1200x0/smart/filters:format(webp):contrast(8):quality(75)/https://static4.libertatea.ro/wp-content/uploads/2020/09/golden-retriever-cat-de-usor-se-dreseaza-si-ce-personalitate-are-cel-mai-indragit-caine.jpg",
                microchip_number: "123456789012353",
            },
            {
                name: "Hazel",
                species: SPECIES.IEPURE,
                breed: "Rex",
                age: 2,
                gender: GENDERS.MASCUL,
                size: SIZES.MIC,
                color: "Bej",
                health_status: HEALTH_STATUSES.BOLNAV,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-12-10",
                notes: "Prietenos cu copiii.",
                image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Fast_Track%2C_Lilac_Mini_Rex.jpg",
                microchip_number: "123456789012354",
            },
            {
                name: "Coco",
                species: SPECIES.IEPURE,
                breed: "Mini Rex",
                age: 1,
                gender: GENDERS.MASCUL,
                size: SIZES.MIC,
                color: "Alb și negru",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.REZERVAT,
                arrival_date: "2024-01-05",
                notes: "Liniștită și blândă.",
                image: "https://www.thesprucepets.com/thmb/VYDopMBfK6m_aCTAgiShehlZChE=/2048x0/filters:no_upscale():strip_icc()/Mini_rex_bunny-0bc79db3d2d54b53a9fc18e54e479883.jpeg",
                microchip_number: "123456789012355",
            },
            {
                name: "Kiwi",
                species: SPECIES.PAPAGAL,
                breed: "Peruș",
                age: 1,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MIC,
                color: "Verde și galben",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.ADOPTAT,
                arrival_date: "2024-02-01",
                notes: "Ciripitor și vorbăreț.",
                image: "https://i0.wp.com/www.australiangeographic.com.au/wp-content/uploads/2021/10/Budgerigar-fact-file.jpg?fit=1800%2C946&ssl=1",
                microchip_number: "123456789012356",
            },
            {
                name: "Luna",
                species: SPECIES.PAPAGAL,
                breed: "Cockatiel",
                age: 1,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MIC,
                color: "Galben",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-02-10",
                notes: "Adoră muzica.",
                image: "https://media.zenfs.com/en/parade_pets_articles_328/06fb5fa596e6a9c7405d06d921e6a141",
                microchip_number: "123456789012357",
            },
            {
                name: "Bella",
                species: SPECIES.CÂINE,
                breed: "Pudel",
                age: 2,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MEDIU,
                color: "Alb",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-01-20",
                notes: "Îi place să fie îngrijită.",
                image: "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2023/09/06151834/Poodle-standing-in-the-garden.jpg",
                microchip_number: "123456789012358",
            },
            {
                name: "Rocky",
                species: SPECIES.CÂINE,
                breed: "Boxer",
                age: 2,
                gender: GENDERS.MASCUL,
                size: SIZES.MARE,
                color: "Maro",
                health_status: HEALTH_STATUSES.SUB_TRATAMENT,
                vaccinated: false,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-08-30",
                notes: "Protectiv și loial.",
                image: "https://cdn.britannica.com/46/233846-050-8D30A43B/Boxer-dog.jpg",
                microchip_number: "123456789012390",
            },
            {
                name: "Snowball",
                species: SPECIES.IEPURE,
                breed: "Olandez",
                age: 1,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MIC,
                color: "Negru și alb",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-03-01",
                notes: "Foarte pufoasă și liniștită.",
                image: "https://www.thesprucepets.com/thmb/qs-qLxHPeQRsj9QSHItpaFTwjOc=/2020x0/filters:no_upscale():strip_icc()/GettyImages-153016104-2e02cc46fd854d30a0e1eaabab6ea82e.jpg",
                microchip_number: "123456789012359",
            },
            {
                name: "Fluffy",
                species: SPECIES.IEPURE,
                breed: "Angora",
                age: 1,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MIC,
                color: "Alb",
                health_status: HEALTH_STATUSES.BOLNAV,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-01-20",
                notes: "Necesită periere zilnică.",
                image: "https://www.zooplus.co.uk/magazine/wp-content/uploads/2022/03/white-angora-rabbit-on-grass.jpeg",
                microchip_number: "123456789012360",
            },
            {
                name: "Zara",
                species: SPECIES.PISICĂ,
                breed: "Persană",
                age: 3,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MEDIU,
                color: "Crem",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.ADOPTAT,
                arrival_date: "2024-12-01",
                notes: "Calmă și elegantă.",
                image: "https://cdn.prod.website-files.com/659c0b0024c127bdbe890959/673a2eb3c1d361675009f9b7_31.jpg",
                microchip_number: "123456789012361",
            },
            {
                name: "Simba",
                species: SPECIES.PISICĂ,
                breed: "Maine Coon",
                age: 3,
                gender: GENDERS.MASCUL,
                size: SIZES.MEDIU,
                color: "Portocaliu",
                health_status: HEALTH_STATUSES.SUB_TRATAMENT,
                vaccinated: false,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-03-10",
                notes: "Are nevoie de o dietă specială.",
                image: "https://catastic.pet/wp-content/uploads/2023/03/maine-coon-origin.jpg",
                microchip_number: "123456789012362",
            },
            {
                name: "Daisy",
                species: SPECIES.CÂINE,
                breed: "Shih Tzu",
                age: 1,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MEDIU,
                color: "Negru și alb",
                health_status: HEALTH_STATUSES.BOLNAV,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-02-28",
                notes: "Micuță și vioaie.",
                image: "https://mediacdn.libertatea.ro/unsafe/1260x708/smart/filters:format(webp):contrast(8):quality(75)/https://static4.libertatea.ro/wp-content/uploads/2020/09/shih-tzu-cum-se-ingrijeste-un-caine-de-rasa--ce-personalitate-are-shih-tzu.jpg",
                microchip_number: "123456789012363",
            },
            {
                name: "Mango",
                species: SPECIES.PAPAGAL,
                breed: "Lovebird",
                age: 3,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MIC,
                color: "Portocaliu",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-03-05",
                notes: "Foarte curioasă și jucăușă.",
                image: "https://cdn.download.ams.birds.cornell.edu/api/v2/asset/623495051/1200",
                microchip_number: "123456789012364",
            },
            {
                name: "Skye",
                species: SPECIES.PAPAGAL,
                breed: "Macaw",
                age: 2,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MIC,
                color: "Albastru",
                health_status: HEALTH_STATUSES.SUB_TRATAMENT,
                vaccinated: true,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2023-11-01",
                notes: "Are nevoie de spațiu pentru a zbura.",
                image: "https://lafeber.com/pet-birds/wp-content/uploads/2024/11/shutterstock_2052377168.jpg",
                microchip_number: "123456789012365",
            },
            {
                name: "Oscar",
                species: SPECIES.CÂINE,
                breed: "Teckel",
                age: 4,
                gender: GENDERS.MASCUL,
                size: SIZES.MEDIU,
                color: "Maro",
                health_status: HEALTH_STATUSES.SUB_TRATAMENT,
                vaccinated: true,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.ADOPTAT,
                arrival_date: "2024-03-15",
                notes: "Are o accidentare la un picior.",
                image: "https://images.ctfassets.net/550nf1gumh01/yh0l63Foctzv7067YDNhO/e391cd9ef39818a77484e5b1fd29f5bc/iStock-145053225.jpg?q=90&w=1240",
                microchip_number: "123456789012366",
            },
            {
                name: "Coco",
                species: SPECIES.PAPAGAL,
                breed: "African Grey",
                age: 4,
                gender: GENDERS.MASCUL,
                size: SIZES.MEDIU,
                color: "Gri",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2024-10-20",
                notes: "Extrem de inteligent.",
                image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Psittacus_erithacus_-perching_on_tray-8d.jpg",
                microchip_number: "123456789012367",
            },
            {
                name: "Spots",
                species: SPECIES.CÂINE,
                breed: "Dalmațian",
                age: 3,
                gender: GENDERS.MASCUL,
                size: SIZES.MARE,
                color: "Alb cu pete negre",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: false,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.REZERVAT,
                arrival_date: "2025-03-23",
                notes: "Îi place să se joace și să meargă la plimbare.",
                image: "https://cdn.britannica.com/47/236047-050-F06BFC5E/Dalmatian-dog.jpg",
                microchip_number: "123456789012368",
            },
            {
                name: "Ra",
                species: SPECIES.PISICĂ,
                breed: "Sphynx",
                age: 2,
                gender: GENDERS.MASCUL,
                size: SIZES.MEDIU,
                color: "Gri",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2025-03-24",
                notes: "Extrem de afectuos, curios și adoră atenția umană.",
                image: "https://paradepets.com/.image/w_3840,q_auto:good,c_fill,ar_4:3/MjAyMDQ4Nzk3MTkzMjgzMTg1/sphynx-cat-3.jpg",
                microchip_number: "123456789012369",
            },
            {
                name: "Kitsu",
                species: SPECIES.CÂINE,
                breed: "Shiba Inu",
                age: 2,
                gender: GENDERS.FEMELĂ,
                size: SIZES.MEDIU,
                color: "Auriu",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: true,
                sterilized: true,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2025-03-24",
                notes: "Independentă, alertă și adesea afișează o personalitate îndrăzneață și energică.",
                image: "https://a-us.storyblok.com/f/1016262/5472x3648/807b733cdf/shiba-inu.jpeg",
                microchip_number: "123456789012370",
            },
            {
                name: "Nugget",
                species: SPECIES.HAMSTER,
                breed: "Sirian",
                age: 1,
                gender: GENDERS.MASCUL,
                size: SIZES.MIC,
                color: "Auriu",
                health_status: HEALTH_STATUSES.SĂNĂTOS,
                vaccinated: false,
                sterilized: false,
                adoption_status: ADOPTION_STATUSES.DISPONIBIL,
                arrival_date: "2025-04-17",
                notes: "Micuț și drăguț",
                image: "https://www.zooplus.ro/ghid/wp-content/uploads/2022/08/Hamster-sirian-pe-o-piatra-in-gradina.webp",
                microchip_number: "123456789012371",
            }
        ]);
        console.log("Animals added.");
    } else {
        console.log("Animals already exist");
    }
};
